In [1]:
import ipynb.fs 
import pandas as pd
import numpy as np
import re
from .defs.Create_grafics import preparation

In [2]:
new_csv1 = pd.read_excel("result_with_3_colums.xlsx", index_col=0,
    converters={'file_code': str,'class': str ,'date':pd.to_datetime})
result = pd.read_excel('result_count.xlsx', index_col=0, dtype=float)
dates = pd.read_excel('dates.xlsx', index_col=0, 
                      converters={'start_period': pd.to_datetime,'end_period': pd.to_datetime})

In [3]:
result

,Top/politics/healthcarepolicy/safetysteps,Top/politics,Top/science/developingvaccine,Top/economy/coronabusiness,Top/society,Top/events,Top/health/recover,Top/technologies/developingofequipment,Top/society/potentialdeath,Top/politics/healthcarepolicy/transport,...,Top/economy,Top/health/illness,Top/economy/coronacrisis,Top/economy/coronajobloss,Top/politics/healthcarepolicy/entertaiment,Top/politics/healthcarepolicy/education,Top/coronavirus,Top/events/onlinetransformed,Top/politics/criminal,Top/society/producthisteria
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,3.0,0.0,0.0,7.0,9.0,0.0,0.0,0.0,0.0,...,8.0,1.0,5.0,0.0,0.0,0.0,8.0,0.0,0.0,1.0
2,3.0,27.0,0.0,0.0,18.0,38.0,1.0,0.0,1.0,4.0,...,5.0,4.0,5.0,1.0,5.0,3.0,23.0,0.0,0.0,0.0
3,11.0,21.0,1.0,1.0,27.0,37.0,2.0,1.0,0.0,17.0,...,15.0,3.0,9.0,9.0,18.0,6.0,50.0,4.0,4.0,2.0
4,11.0,10.0,4.0,3.0,24.0,23.0,6.0,1.0,3.0,17.0,...,18.0,5.0,10.0,7.0,6.0,5.0,64.0,3.0,0.0,2.0
5,18.0,14.0,1.0,3.0,38.0,31.0,14.0,6.0,3.0,16.0,...,35.0,20.0,20.0,18.0,8.0,3.0,104.0,4.0,3.0,1.0
6,17.0,9.0,0.0,0.0,39.0,42.0,20.0,7.0,1.0,13.0,...,17.0,18.0,12.0,12.0,5.0,0.0,103.0,4.0,0.0,6.0
7,40.0,24.0,4.0,2.0,82.0,81.0,27.0,3.0,5.0,24.0,...,28.0,35.0,26.0,19.0,28.0,2.0,194.0,4.0,8.0,3.0
8,45.0,58.0,0.0,2.0,115.0,149.0,25.0,3.0,5.0,26.0,...,30.0,31.0,17.0,23.0,29.0,5.0,204.0,7.0,5.0,0.0
9,31.0,24.0,1.0,0.0,45.0,78.0,12.0,3.0,4.0,9.0,...,23.0,15.0,16.0,10.0,15.0,4.0,130.0,3.0,4.0,3.0
10,24.0,23.0,5.0,1.0,42.0,81.0,17.0,3.0,1.0,8.0,...,30.0,22.0,12.0,12.0,6.0,1.0,139.0,3.0,1.0,0.0
11,31.0,15.0,2.0,1.0,59.0,79.0,13.0,0.0,1.0,11.0,...,23.0,25.0,11.0,6.0,9.0,0.0,132.0,4.0,3.0,0.0
12,22.0,51.0,3.0,3.0,75.0,123.0,22.0,1.0,2.0,10.0,...,44.0,24.0,22.0,12.0,11.0,1.0,178.0,2.0,3.0,0.0
13,13.0,38.0,3.0,1.0,63.0,97.0,20.0,2.0,2.0,3.0,...,25.0,11.0,10.0,11.0,6.0,0.0,129.0,2.0,1.0,1.0
14,16.0,39.0,2.0,0.0,64.0,111.0,13.0,3.0,0.0,9.0,...,23.0,16.0,12.0,11.0,7.0,0.0,154.0,4.0,1.0,1.0
15,11.0,34.0,3.0,0.0,55.0,84.0,17.0,2.0,0.0,3.0,...,16.0,15.0,3.0,11.0,7.0,0.0,127.0,2.0,0.0,2.0
16,21.0,55.0,2.0,0.0,82.0,120.0,27.0,1.0,5.0,5.0,...,28.0,22.0,13.0,10.0,6.0,1.0,164.0,3.0,0.0,2.0

In [4]:
new_csv1

     file_code                                              class       date
0        bbc_0                      Top/politics/healthcarepolicy 2020-03-22
1        bbc_0  Top/politics/healthcarepolicy/quarntine_streng... 2020-03-22
2        bbc_0                                         Top/events 2020-03-22
3        bbc_0                       Top/events/onlinetransformed 2020-03-22
4        bbc_0                           Top/economy/coronacrisis 2020-03-22
...        ...                                                ...        ...
9706    zn_842                                       Top/politics 2020-04-06
9707    zn_842  Top/politics/healthcarepolicy/quarntine_streng... 2020-04-06
9708    zn_843                                 Top/health/recover 2020-04-07
9709    zn_843                           Top/health/dissemination 2020-04-07
9710    zn_843                                   Top/technologies 2020-04-07

[9711 rows x 3 columns]

In [5]:
dates

   start_period end_period
0    2020-03-03 2020-03-06
1    2020-03-07 2020-03-10
2    2020-03-11 2020-03-14
3    2020-03-15 2020-03-18
4    2020-03-19 2020-03-22
5    2020-03-23 2020-03-26
6    2020-03-27 2020-03-30
7    2020-03-31 2020-04-03
8    2020-04-04 2020-04-07
9    2020-04-08 2020-04-11
10   2020-04-12 2020-04-15
11   2020-04-16 2020-04-19
12   2020-04-20 2020-04-23
13   2020-04-24 2020-04-27
14   2020-04-28 2020-05-01
15   2020-05-02 2020-05-05
16   2020-05-06 2020-05-09

In [6]:
my_classes = list(set(new_csv1['class']))
my_classes

['Top/economy',
 'Top/events/onlinetransformed',
 'Top/health/recover',
 'Top/politics/healthcarepolicy',
 'Top/politics/healthcarepolicy/transport',
 'Top/science',
 'Top/politics',
 'Top/politics/criminal',
 'Top/politics/healthcarepolicy/quarntine_strengthening',
 'Top/technologies/developingofequipment',
 'Top/science/existeddrugs',
 'Top/technologies',
 'Top/events',
 'Top/science/developingvaccine',
 'Top/society/producthisteria',
 'Top/economy/coronabusiness',
 'Top/politics/healthcarepolicy/safetysteps',
 'Top/society',
 'Top/society/potentialdeathhisteria',
 'Top/health/dissemination',
 'Top/society/potentialdeath',
 'Top/health/illness',
 'Top/coronavirus',
 'Top/economy/coronacrisis',
 'Top/politics/healthcarepolicy/education',
 'Top/economy/coronajobloss',
 'Top/health',
 'Top/politics/healthcarepolicy/entertaiment',
 'Top/economy/crisis',
 'Top/society/death',
 'Top/events/coronacanceledevents',
 'Top/society/familytroubles',
 'Top/economy/coronaimport',
 'Top/science/developingnewdrugs']

**max_class** is list of top category in each period

In [61]:
max_class=pd.Series(result.columns[np.argmax(result.values,axis=1)])
final=pd.DataFrame(result.lookup(max_class.index,max_class),max_class)

In [62]:
max_class

0     Top/coronavirus
1          Top/events
2          Top/events
3     Top/coronavirus
4     Top/coronavirus
5     Top/coronavirus
6     Top/coronavirus
7     Top/coronavirus
8     Top/coronavirus
9     Top/coronavirus
10    Top/coronavirus
11    Top/coronavirus
12    Top/coronavirus
13    Top/coronavirus
14    Top/coronavirus
15    Top/coronavirus
16    Top/coronavirus
dtype: object

In [58]:
sum_of_each_period = result.sum(axis=1)
sum_of_each_period = np.array(list(sum_of_each_period))
sum_of_each_period

array([1.000e+00, 5.500e+01, 1.700e+02, 3.030e+02, 3.120e+02, 5.190e+02,
       4.690e+02, 9.030e+02, 1.077e+03, 6.340e+02, 6.090e+02, 5.960e+02,
       8.680e+02, 5.980e+02, 6.780e+02, 5.560e+02, 7.910e+02])

**get_count_texts_in_period** 
<br> This function return count of articles in each period (type=np.array)

In [42]:
def get_count_texts_in_period(result_tabes, dates_of_preiod):
    counts = np.array([])
    for i in range(len(dates_of_preiod)):
        df_temp = result_tabes[(dates_of_preiod['start_period'][i] <= result_tabes['date']) &
                               (result_tabes['date'] <= dates_of_preiod['end_period'][i])]['file_code']
        count = len(set(df_temp))
        counts = np.append(counts, values=count )
        print(count)
    return counts

In [43]:
counts_each_period = get_count_texts_in_period(new_csv1, dates)
counts_each_period

1
16
54
73
79
125
127
242
310
187
207
191
267
231
255
195
265

array([  1.,  16.,  54.,  73.,  79., 125., 127., 242., 310., 187., 207.,
       191., 267., 231., 255., 195., 265.])

**Mean1** is sum in clasifier delete on a count of article on eachperiod

In [59]:
mean1 = sum_of_each_period / counts_each_period
mean1

array([1.        , 3.4375    , 3.14814815, 4.15068493, 3.94936709,
       4.152     , 3.69291339, 3.73140496, 3.47419355, 3.39037433,
       2.94202899, 3.12041885, 3.25093633, 2.58874459, 2.65882353,
       2.85128205, 2.98490566])

In [60]:
mean1.mean()

3.207278022693148